(print-length 20)
(load "euler.so")
(import (euler))
(define (pi N)
  (length (primes N)))

(for-each (lambda (N)
	    (format #t "~a = 2^~a~%" (expt 2 N) N)
	    (time (pi (expt 2 N))))
	  (iota 31))
