;; visit all permutations of vector A
(define algorithm-P
  (lambda (A visit)
    (define n (vector-length A))
    (define j)
    (define s)
    (define q)
    (define C (make-fxvector (fx1+ n) 0))
    (define O (make-fxvector (fx1+ n) 1))
    (define (P2)
      (visit A)
      (P3))
    (define (P3)
      (set! j n)
      (set! s 0)
      (P4))
    (define (P4)
      (set! q (fx+ (fxvector-ref O j)
                   (fxvector-ref C j)))
      (cond ((fx< q 0) (P7))
	    ((fx= q j) (P6))
	    (else (P5))))
    (define (P5)
      (vector-swap! A
                    (fx+ j s (- (fxvector-ref C j)) -1)
                    (fx+ j s (- q) -1))
      (fxvector-set! C j q)
      (P2))
    (define (P6)
      (unless (fx= j 1)
	(inc! s)
	(P7)))
    (define (P7)
      (fxvector-set! O j (fx- (fxvector-ref O j)))
      (dec! j)
      (P4))
    (P2)))

