;; macros idk how to do properly
(define-syntax for
  (lambda (x)
    (syntax-case x (in)
      ((_ (x y) in X e ...)
       #'(let loop ((xs X))
	   (unless (null? xs)
	     (let ((x (car xs)))
	       (for y in (cdr xs)
		    e ...)
	       (loop (cdr xs))))))
      ((_ (x y ...) in X e ...)
       #'(let loop ((xs X))
	   (unless (null? xs)
	     (let ((x (car xs)))
	       (for (y ...) in (cdr xs)
		    e ...)
	       (loop (cdr xs))))))
      ((_ x in X e ...)
       #'(let loop ((xs X))
	   (unless (null? xs)
	     (let ((x (car xs)))
	       e ...
	       (loop (cdr xs)))))))))

(define-syntax for/V
  (lambda (x)
    (syntax-case x (in)
      ((_ x in V e ...)
       #'(let ((n (vector-length V)))
	   (let loop ((i 0))
	     (unless (= i n)
	       (let ((x (vector-ref V i)))
		 e ...)
	       (loop (1+ i)))))))))
